SOURCES1 = newcow.c cow.c cow_traitement.c cow_affichage.c chaine_operation.c
EXE1 = newcow

$(EXE1): 
	gcc $(SOURCES1) -o $(EXE1)


SOURCES2 = wildcow.c
EXE2 = wildcow

$(EXE2): 
	gcc $(SOURCES2) -o $(EXE2)