CC=gcc

all: reading_cow

reading_cow: reading_cow.c cow.c cow_traitement.c cow_affichage.c chaine_operation.c printf_color.c cow_read.c
	$(CC) -o reading_cow reading_cow.c cow.c cow_traitement.c cow_affichage.c chaine_operation.c printf_color.c cow_read.c