#!/bin/bash

for i in $(seq 10)
do
    clear
    if [ $i -eq 10 ]        # test si i est égale à 10
    then
        cowsay -T "U " $i   # si oui la vache tire la langue
    else
        cowsay $i
        sleep 1
    fi
done