#!/bin/bash

for i in $(seq $1)
do
    clear
    if [ $i -eq $1 ]        # test si i est égale au premier argument
    then
        cowsay -T "U " $i   # si oui la vache tire la langue
    else
        cowsay $i
        sleep 1
    fi
done